### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [ahmedfgad/AndroidFlask#1]
Hi, and thanks for your cool project! Did you already decide what license to put it under (like, Apache, MIT, GPL…)?

**Comment by IzzySoft** [comment]
@ahmedfgad any decision yet?

**Comment by ahmedfgad** [comment]
Hi,

Thanks for your interest in the project.

MIT license is selected.

Good luck.

**Comment by IzzySoft** [comment]
Perfect, thanks! Good luck and health to you as well!
