### ISSUE TITLE
How to execute a shell script command after {return "Image(s) Uploaded Successfully. Come Back Soon."}? 

### ISSUE THREAD

**Issue by mm840511m** [ahmedfgad/AndroidFlask#2]
Hi, if I want to execute a shell script command (ex. subprocess.run(['./test.sh'])) after the return statement, what should I do?

**Comment by ahmedfgad** [comment]
Hi,

You can check [this question](https://stackoverflow.com/questions/48994440/execute-a-function-after-flask-returns-response) for information about doing some processing after Flask returns a response.

**Comment by Frankfengfeng** [comment]
hello my friend ! I have been using your project , but I can't select an image by saying "Please make sure the selected file is an image", I can't find the solution in your blog ,so if you can teach me how can i solve this problem? Thank you!

**Comment by ahmedfgad** [comment]
> hello my friend ! I have been using your project , but I can't select an image by saying "Please make sure the selected file is an image", I can't find the solution in your blog ,so if you can teach me how can i solve this problem? Thank you!

Hello @Frankfengfeng 
Could you check whether the app has permission to access the files? Go to the app settings and check please.

**Comment by Frankfengfeng** [comment]
yes, in the AndroidManifest.xml I have two permission  
   <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

I have try upload the .bmp and .jpg in the /sdcard/DCIM  but it always ask me to check if is an image

**Comment by ahmedfgad** [comment]
Not the manifest file. I mean check the app settings after you install it to an Android device.

**Comment by Frankfengfeng** [comment]
oh man! Thanks for your patience! sorry I just learn Android for days , you mean the app permission in the android studio SIMULATOR for the app，thanks again！
