### ISSUE TITLE
Please Make Sure the Selected File is an image - error

### ISSUE THREAD

**Issue by reboisn** [ahmedfgad/AndroidFlask#4]
Hi, currently this error shows no matter what type of image file seems to be selected. Any advice please? Thank you

**Comment by ahmedfgad** [comment]
Hi,

Could you check selecting an image from the Downloads directory?

**Comment by reboisn** [comment]
Hello, unfortunately if I do that I get the 'Something Went Wrong' toast

**Comment by ahmedfgad** [comment]
Are you sure the Android app has permission to access media files? Please check the app permissions.

**Comment by reboisn** [comment]
Yes, I checked the manifest and read external storage is permitted.

**Comment by ahmedfgad** [comment]
I do not mean the manifest. I mean the permissions of the installed app in your Android phone. That is going to Settings>Apps> ... Permissions

**Comment by reboisn** [comment]
Yes, this was the issue. Many thanks
