### ISSUE TITLE
Different image paths

### ISSUE THREAD

**Issue by reboisn** [ahmedfgad/AndroidFlask#5]
Hi, anyway to make your app work with the path to an newly created folder other than the standard Android Gallery?  Eg:

File storageDir = getExternalFilesDir(Environment.DIRECTORY_DCIM);

When I try to add an image from my newly created folder DCIM (in Internal Storage - Android- data-...) I get the 'Something went wrong' toast.

Thanks!

**Comment by ahmedfgad** [comment]
Hi,

I am sorry as I am not an expert in Android development. You can look for Android code about that and add it to the project.

**Comment by reboisn** [comment]
OK thanks anyway
